title: Fahad Imaduddin # your name (or website title) here
logo: "/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Fullstack Engineer
  <br><br>
  <a href="mailto:fahadimaduddin@hotmail.com">fahadimaduddin@hotmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/fahadimaduddin/">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/fahadimaduddin/">Github Profile</a> 
theme: jekyll-theme-minimal
